# Generated by Django 2.1.4 on 2019-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('komentar', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
